# Week 1 

The purpose of this week's exercise is twofold: First, to introduce you to Numpy and making you familiar with the library and some of its pitfalls. Second, you will apply this to estimate the linear model using OLS.

(Jupyter Basics) A few things to note about Jupyter Notebook (ipynb files). (1) Notebooks may run cells individually by selecting a cell and using ctrl + enter. (2) Each notebook runs on a kernel which is selected by the user the first time a cell is run. (3) The kernel "stores" variables as the code is run. To utilize code in a proceeding cell, it is neccessary to run the previous cell. Be careful with overlapping variable names across cells. It becomes messy to clean up.

* The kernel is your installation of Python. Make sure your installation of Python is visible to your environment.

Please note that some of the exercises are purposefully made to return errors. Take the time to identify why they occur.

## A short introduction to Numpy and Linear Algebra (Linalg)
First, import all necessary packages. If you are missing a package, you can either install it through your terminal using pip, or an Anaconda terminal using conda.

In [46]:
import numpy as np # We import the package numpy and name it "np"
from numpy import linalg as la 
# We import the subpackage linalg from numpy and name it "la". 
# In most cases, importing a subpackage is not neccessary when the overarching package has been imported, 

# although lacking dependencies may change functionality in some cases.
from numpy import random as random
from tabulate import tabulate
#(NB if you havent got tabulate yet, install it using !pip install tabulate)
from matplotlib import pyplot as plt

### Entering matrices manually
To create a $1\times9$ *row* vector write,

In [47]:
row = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
scalar_x = 5
print(row)

[1 2 3 4 5 6 7 8 9]


To create a $9\times1$ *column* vector write,

In [48]:
col = np.array([[1], [2], [3], [4], [5], [6], [7], [8], [9]])
print(col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


An easier method is to define a row vector, and transpose it. Notice the double [[]]. Try to see what happens if you transpose a row vector using only [].

In [49]:
col = np.array([[1, 2, 3, 4, 5, 6, 7, 8, 9]]).T
print(col)

[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]


**A short note on numpy vectors**
Numpy does not treat vectors and matrices the same. A *true* numpy vector has the shape (k,), . The shape of a numpy array is an attribute, how do you call this attribute for the `row` and `col` arrays? What is the shape of the `row.T` array? 

In [50]:
# Call the shape attribute for the row and col vars. Check the shape of col.T
# FILL IN HERE

print(row.shape)
print(col.shape)
print(col.T.shape)


(9,)
(9, 1)
(1, 9)


To create a matrix, you combine what you have learned to manually create a $3 \times 3$ matrix called x, that has the numbers 0 to 8.

In [51]:
x = np.array([[0,1,2],[3,4,5],[6,7,8]]) # FILL IN HERE
x

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

Create the same $3 \times 3$ using `np.arange()` and np.reshape()

In [52]:
x = np.arange(8) # FILL IN HERE
x


array([0, 1, 2, 3, 4, 5, 6, 7])

### Matrix calculations 
There are several types of matrix calculations available to us with the numpy library, and we will introduce some here.

For matrix **multiplication** you can for the matrices `a` and `b` use `a@b`, `np.dot(a, b)` or `a.dot(b)`

Perform matrix multiplication on the following:
- `row`$\cdot$`row'`, `row'`$\cdot$`row`, `row`$\cdot$`row`;
- `col`$\cdot$`col'`, `col'`$\cdot$`col`, `col`$\cdot$`col`;
- `x`$\cdot$`x`, `row`$\cdot$`col'`, `col`$\cdot$`row'`.

Does the `row` vector behave as you would expect?

In [53]:
print(row@row)
print(np.dot(row, row))
print(row.dot(row))

285
285
285


In [54]:
print(row@row.T)
print(col@col.T)
print(col.T@col)


285
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[285]]


In [55]:
print(x@x)
print(col.T@row)
#print(row@col.T) # throws a mismatch error. Multiplies 1x9 with 1x9.
print(str(row) + " a 1x9 vector")
print(str(col.T) + " a 1x9 vector")


140
[285]
[1 2 3 4 5 6 7 8 9] a 1x9 vector
[[1 2 3 4 5 6 7 8 9]] a 1x9 vector


What happens if you use `*` and `/` operators on the same pairs as above? Does the `col` vector behave as you would expect?

In [56]:
print(row*col.T) # no. It simply multiplies the scalars on the column, which isn't what we want.
print(row.T*row) # difference between 
print(row*row) # elementwise multiplication, not matrix multiplication
print(row/row.T) # elementwise division, not matrix division
print(row.T/row) # elementwise division, not matrix division
print(row/row) # elementwise division, not matrix division

[[ 1  4  9 16 25 36 49 64 81]]
[ 1  4  9 16 25 36 49 64 81]
[ 1  4  9 16 25 36 49 64 81]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]
[1. 1. 1. 1. 1. 1. 1. 1. 1.]


In [57]:
print(col.T@col) # Correct -> produces a single scalar. The transposed column vector is a row. Multiplying a matrix row * column yields a scalar.
print(col.T*col) # Multiplies it elementwise.
print(col*col)
print(col/col.T)
print(col.T/col)
print(col/col)

[[285]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[ 1]
 [ 4]
 [ 9]
 [16]
 [25]
 [36]
 [49]
 [64]
 [81]]
[[1.         0.5        0.33333333 0.25       0.2        0.16666667
  0.14285714 0.125      0.11111111]
 [2.         1.         0.66666667 0.5        0.4        0.33333333
  0.28571429 0.25       0.22222222]
 [3.         1.5        1.         0.75       0.6        0.5
  0.42857143 0.375      0.33333333]
 [4.         2.         1.33333333 1.         0.8        0.66666667
  0.57142857 0.5        0.44444444]
 [5.         2.5        1.66666667 1.25       1.         0.83333333
  0.71428571 0.625      0.55555556]
 [6.         3.         2.         1.5        1.2        1.
  0.85714286 0.75       0.66666667]
 [7.         3.5        2.33333333 1.75       1.4        

In [58]:

print(row*col)
print(col*row)
print(x/x)
print(row/col)
print(col/row)

[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[[ 1  2  3  4  5  6  7  8  9]
 [ 2  4  6  8 10 12 14 16 18]
 [ 3  6  9 12 15 18 21 24 27]
 [ 4  8 12 16 20 24 28 32 36]
 [ 5 10 15 20 25 30 35 40 45]
 [ 6 12 18 24 30 36 42 48 54]
 [ 7 14 21 28 35 42 49 56 63]
 [ 8 16 24 32 40 48 56 64 72]
 [ 9 18 27 36 45 54 63 72 81]]
[nan  1.  1.  1.  1.  1.  1.  1.]
[[1.         2.         3.         4.         5.         6.
  7.         8.         9.        ]
 [0.5        1.         1.5        2.         2.5        3.
  3.5        4.         4.5       ]
 [0.33333333 0.66666667 1.         1.33333333 1.66666667 2.
  2.33333333 2.66666667 3.        ]
 [0.25       0.5        0.75       1.         1.25       1.5
  1.75       2.         2.25      ]
 [0.2        0.4        0.6        0.8 

/var/folders/nc/mxht2rvj70z567nmv3cxrryc0000gn/T/ipykernel_18470/1316177879.py:3: RuntimeWarning: invalid value encountered in divide
  print(x/x)


For OLS we need to be able to calculate the inverse. This is done with the `linalg` submodule. Create a new matrix that we can calculate the inverse on. Why can't we take the inverse of `x`?

In [59]:
print(np.linalg) # a function of numpy
print(x)
#x_inv = np.linalg.inv(x) # this doesn't work since x is not a square matrix, its a 1x9 matrix.


# A correct example:
y = np.array([[1, 2], [3, 4]])
y_inv = np.linalg.inv(y) # FILL IN HERE
print(y)
print(y_inv)

<module 'numpy.linalg' from '/Users/noahcarelse/Library/CloudStorage/ProtonDrive-noahcarelse@protonmail.com-folder/Offline mappe/Universitet/01 - Cand polit/1. semester/01 - Advanced Microeconometrics/Advanced-Microeconometrics-UCPH-2025/.venv/lib/python3.13/site-packages/numpy/linalg/__init__.py'>
[0 1 2 3 4 5 6 7]
[[1 2]
 [3 4]]
[[-2.   1. ]
 [ 1.5 -0.5]]


What do we normally need to check before we take the inverse? What `numpy.linalg` methods can we use to help us check for this?

In [60]:
# Again, check whether the matrix is square, singlular or non-singular.

### Stack vectors or matrices together
If you have several 1-D vectors (has the shape (k,)), you can use `np.column_stack()` to get a matrix with the input vectors put together as column.

If you have matrices (or arrays) that are multidimensional (have the shape (k, t)), you can use `np.hstack()` (means horizontal stack). This is very useful if you already have a matrix, and you want to add a vector.

(i) Try to make a matrix with two `row` vectors, this should give you a $9 \times 2$ vector.

(ii) Make a new vector, and add it to the `x` matrix. This should then be a $3 \times 4$ matrix

In [61]:
# i)
print(row)
stacked_row_col = np.column_stack((row, row)) # Takes the row vector and makes it a column, then stacks it next to col.
print(stacked_row_col)
print(" ")


# ii) Make a new vector, and add it to the x matrix. This should be a 3 times 4 matrix.
# so 3 x 4 matrix.
x = np.arange(9) # the arange(9) produces 0 - 8 -> 9 elements
y = np.array([[1],[2],[3]]) # produce a 3x1 matrix (KxT = column x rows)
np.hstack((x.reshape(3,3), y)) # FILL IN HERE

[1 2 3 4 5 6 7 8 9]
[[1 1]
 [2 2]
 [3 3]
 [4 4]
 [5 5]
 [6 6]
 [7 7]
 [8 8]
 [9 9]]
 


array([[0, 1, 2, 1],
       [3, 4, 5, 2],
       [6, 7, 8, 3]])

### Other methods that you need to know.
The numpy library is vast. Some other methods that are useful are `ones`, `diag`, `diagonal`, `eye`.

## Exercise 1 - Data generation
### 1.1 
Create a synthetic dataset with the following characteristics

\begin{align}
    y_i &= \beta_0 + x_{1i}\beta_1 + x_{2i}\beta_2 + \varepsilon_i
\end{align}

where $\beta_0=1$, $\beta_1 = -0.5$, $\beta_2 = 2$, $x_{1i} \sim \mathcal{N}(0, 4)$, $x_{2i} \sim \mathcal{N}(5, 9)$, $\varepsilon_i \sim \mathcal{N}(0, 1)$, and $(x_{1i},x_{2i})$ and $\varepsilon_i$ are independent, and where $i = 0, ..., 99$. <br>

In [62]:
# Create a seed to always have identical draws.
# Instance a random number generator using this seed.
seed = 42
rng = random.default_rng(seed=seed) # rng generator
n = 100 # draws
b = np.array([1, -0.5, 2]).reshape(-1, 1) # beta


# Make random draws from a normal distribution.
def random_draws(n):
    x0 = np.ones(n).reshape(-1,1) # Have to reshape for to a column. x_0 is the constant, but not shown directly in the equation.
    x1 = rng.normal(size=n,loc=0,scale=2).reshape(-1,1) 
    x2 = rng.normal(size=n,loc=5,scale=3).reshape(-1,1)
    eps = rng.standard_normal(n).reshape(-1,1) # error term
    
    # Stack the single columns into a matrix, 
    X = np.hstack((x0, x1, x2)) 
    
    return X, eps



X, eps = random_draws(n)

# Create y using the betas, X and eps.
y = X@b + eps 

# Does y have the dimensions you expect?
print(y.shape) # yes. 100 entries in a column matrix.



(100, 1)


### 1.2 
Imagine that you had not generated the dataset yourself, but that you were given a similar data set that was already collected (generated) and ready to analyze. What would you observe and not observe in that data set?

Possible missing data entries? Or the set seed?

## Exercise 2 - OLS
### 2.1
Remember the mathematical equation for OLS estimation, as we will later use it to estimate the beta coefficients with the data from the previous exercise.<br>
**Write out the OLS estimator in matrix form:**


$\hat{\boldsymbol{\beta}} = \mathbf{X'X}^{-1} \mathbf{X'Y} $ 


*Hint: Look it up on p.57 in Wooldridge*

### 2.2
To perform inference on the OLS estimators, we need to calculate the standard errors for the previously estimates OLS coefficients. Again, make sure you remember its equation, *and write up the OLS standard errors in matrix form:*

$\mathbf{\widehat{Var(\boldsymbol{\hat{\beta}})}} = \hat{\sigma}^2 \mathbf{X'X}^{-1}$, for $\hat{\sigma}^2 = SSR/(N-K)$, <br>

where $SSR = \sum_{i=0}^{N - 1} \hat{u}^2_i$, $N$ is the number of observations, and $K$ is the number of explanatory variables including the constant.

*Hint: Look it up on p.60 in Wooldridge* <br>
*Hint: Remember that the variance estimate is a function of $\hat{\sigma}^2$, which is calculated using SSR*

### 2.3
Estimate $\boldsymbol{\hat{\beta}}$ from the synthetic data set. Furthermore, calculate standard errors and t-values (assuming that the assumptions of the classical linear regression model are satisfied).

In [63]:
def ols_estimation(y, X):
    # Make sure that y and X are 2-D.
    y = y.reshape(-1, 1)
    if len(X.shape)<2:
        X = X.reshape(-1, 1)

    # Estimate beta
    b_hat =  la.inv(X.T@X)@X.T@y  # Fill in here

    # Calculate standard errors
    residual = y - X@b_hat
    sigma = residual.T @ residual / (residual.shape[0] - b.shape[0]) # output is a column with one entry.
    #print(sigma[0][0]) # 
    varb = sigma[0][0] * la.inv(X.T@X) # the covariance matrix, diagonal is variance. The scalar for sigma is at entry [0][0], else it throws a matmul error.
    se = np.sqrt(varb.diagonal().reshape(-1,1)) # reshape so it can fit into the t_value calculations.

    # Calculate t-values
    t_values = b_hat/se
    
    return b_hat, se, t_values, residual


b_hat, se, t_values, residual = ols_estimation(y, X)
print("b_hat values: \n" + str(b_hat))
print("Standard errors: \n" + str(se))
print("t-values: \n" + str(t_values))
print("residuals: \n" + str(residual))

b_hat values: 
[[ 0.91355184]
 [-0.50537828]
 [ 2.0047447 ]]
Standard errors: 
[[0.20537787]
 [0.06725774]
 [0.03555339]]
t-values: 
[[ 4.44815138]
 [-7.51405441]
 [56.38687539]]
residuals: 
[[ 4.08959719e-01]
 [ 1.44052651e+00]
 [ 1.66452937e-01]
 [ 7.06282818e-01]
 [-1.99514466e+00]
 [ 2.92349968e-03]
 [-7.65607777e-01]
 [-1.15466425e+00]
 [-8.27569468e-01]
 [-2.55987744e-01]
 [ 9.81902865e-01]
 [-1.25868565e+00]
 [ 1.02523605e-01]
 [-3.88736198e-01]
 [-2.60946344e-01]
 [ 1.06377630e+00]
 [ 6.01494646e-01]
 [ 1.38949744e+00]
 [-1.05131807e-01]
 [-6.30347973e-01]
 [-1.48554073e-01]
 [ 2.95345158e-01]
 [ 2.49316900e-01]
 [-1.04267244e+00]
 [ 1.36720042e-01]
 [ 2.82085500e-01]
 [ 2.56509570e+00]
 [ 1.96042117e+00]
 [-7.76972820e-01]
 [-2.06835573e-01]
 [-1.37213199e+00]
 [-5.12758091e-01]
 [ 3.63778884e-01]
 [ 1.26298802e+00]
 [-6.38797749e-01]
 [-5.64822064e-01]
 [-2.09025265e+00]
 [-1.20908441e-01]
 [-1.03698002e+00]
 [-5.01192854e-01]
 [-8.12040010e-01]
 [-1.16102360e-02]
 [-1.671814

Python stores vectors as one-dimensional rather than two-dimensional objects. This can sometimes cause havoc when we want to compute matrix products. Compute the outer and inner products of the residuals from above using np.inner() and np.outer(). Compare these with your computed outer and inner products when using matrix multiplication @. When computing outer and inner products of a column vector, a, recall that a'a is the inner product and aa' is the outer product.

In [64]:
res = residual
inner = np.inner(res, res) # it is still a vector.
print("Inner product, first 5 listings: " + str(inner[0][:5])) # a matrix, unexpected behaviour

outer = np.outer(res,res)
print("Outer product, first 5 listings: " + str(outer[0][:5])) # a matrix, as expected

matmul_inner = residual.T@residual
print("matrix multiplication broadcast inner: " + str(matmul_inner)) # a scalar but in a matrix, somewhat expected

matmul_outer = residual@residual.T
print("matrix multiplication broadcast outer, first 5 listings: " + str(matmul_outer[0][:5])) # a matrix, as expected

print('res shape:         ', res.shape)
print('inner shape:       ', inner.shape)
print('outer shape:       ', outer.shape)
print('matmul_inner shape:', matmul_inner.shape)
print('matmul_outer shape:', matmul_outer.shape)


Inner product, first 5 listings: [ 0.16724805  0.58911732  0.06807255  0.28884122 -0.8159338 ]
Outer product, first 5 listings: [ 0.16724805  0.58911732  0.06807255  0.28884122 -0.8159338 ]
matrix multiplication broadcast inner: [[103.88122746]]
matrix multiplication broadcast outer, first 5 listings: [ 0.16724805  0.58911732  0.06807255  0.28884122 -0.8159338 ]
res shape:          (100, 1)
inner shape:        (100, 100)
outer shape:        (100, 100)
matmul_inner shape: (1, 1)
matmul_outer shape: (100, 100)


Now if we flatten the residuals to be stored in Python's default mode (i.e. one-dimensional) what happens?

In [65]:
res = res.flatten()
inner = np.inner(res, res) # a scalar, as expected
outer = np.outer(res,res) # a matrix, as expected
matmul_inner = residual.T@residual # a scalar, but in a matrix, somewhat expected
matmul_outer = residual@residual.T # a matrix, as expected

print('res shape:         ', res.shape)
print('inner shape:       ', inner.shape)
print('outer shape:       ', outer.shape)
print('matmul_inner shape:', matmul_inner.shape)
print('matmul_outer shape:', matmul_outer.shape)
# expected output of the shapes. Matrix multiplication '@' still outputs a matrix, but computes correctly.


res shape:          (100,)
inner shape:        ()
outer shape:        (100, 100)
matmul_inner shape: (1, 1)
matmul_outer shape: (100, 100)


I have written a code to print a table, using the `tabulate` package. You will need to add the row names for this code to work - each row contains a information about the different coefficients on the explanatory variables.

In [82]:
def print_table(row_names, b, b_hat, se, t_values):
    table = []

    # Make a list, where each row contains the estimated and calculated values.
    for index, name in enumerate(row_names):
        table_row = [
            name, b[index], b_hat[index], se[index], t_values[index]
        ]
        table.append(table_row)

    # Print the list using the tabulate class.
    headers = ['', '\u03b2', '\u03b2\u0302 ', 'Se', 't-value']
    print('OLS Estimates:\n')
    print(tabulate(table, headers, floatfmt=['', '.1f', '.3f', '.3f', '.1f']))

row_names = ["b_0", "b_1", "b_2"] # Fill in here
print_table(row_names, b, b_hat, se, t_values) # Fill in here

OLS Estimates:

        β      β̂      Se    t-value
---  ----  ------  -----  ---------
b_0   1.0   0.914  0.205        4.4
b_1  -0.5  -0.505  0.067       -7.5
b_2   2.0   2.005  0.036       56.4


Alternatively, you can print a table which you can paste straight into latex using the following code. This uses panda data frames  which we'll cover next week.

In [ ]:
import pandas as pd

# Note that it also requires the jinja2 package!
dat = pd.DataFrame(zip(b,b_hat.round(4),se.round(4),t_values.round(4)))
dat.columns = ['\u03b2','\u03b2\u0302','se','t-values']
dat.index = ['beta1','beta2','beta3']
print(dat.style.to_latex())

\begin{tabular}{lllll}
 & β & β̂ & se & t-values \\
beta1 & [1.] & [0.9136] & [0.2054] & [4.4482] \\
beta2 & [-0.5] & [-0.5054] & [0.0673] & [-7.5141] \\
beta3 & [2.] & [2.0047] & [0.0356] & [56.3869] \\
\end{tabular}



## Exercise 3 - a simple Monte Carlo Experiment
Carry out a Monte Carlo experiment with $S = 200$ replications and $N = 100$ observations to check if the OLS estimator provides an unbiased estimate of $\boldsymbol{\beta}$
### 3.1
Generate 200 data sets similar to what you did in exercise 1, and estimate $\boldsymbol{\beta}$ on each of them.

*Hint:* Start by making prefilling two arrays using `np.zeros`, one array to store the estimated beta coefficients, and one to store the estimated standard errors. What shape should these arrays have?

Then make a loop where each loop makes a random draw, and then estimates on this random draw. And finally stores the estimated coefficients and standard errors.

In [ ]:
# Initialize the variables and lists
s = 200
n = 100

# Allocate memory for arrays to later fill
b_coeffs = np.zeros((s, b.size))
b_ses = np.zeros((s, b.size))

for i in range(s):
    # Generate data
    X, eps = # Fill in here
    y = # Fill in here

    # Estimate coefficients and variance
    b_hat, se, t_values = # Fill in here

    # Store estimates
    b_coeffs[i, :] = # Fill in here
    b_ses[i, :] = # Fill in here

# Make sure that there are no more zeros left in the arrays.
assert np.all(b_coeffs) and np.all(b_ses), 'Not all coefficients or standard errors are non-zero.'

### 3.2
Do the following three calculations:
- Calculate the means of the estimates (means across simulations)
- Calculate the means of the standard errors (means across simulations)
- Calculate the standard error of the MC estimates

In [ ]:
mean_b_hat = # Fill in here
mean_b_se = # Fill in here
mean_mc_se = # Fill in here

### 3.3
Draw a histogram for the 200 estimates of $\beta_1$. This can be done using matplotlib with the method `plt.hist()`.

In [ ]:
# Fill in here